services:
  nginx-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-manager
    restart: unless-stopped
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
      - "50001:81"   # NPM web UI
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    networks:
      - web

  nodejs:
    build: ./nodejs
    container_name: nodejs
    restart: unless-stopped
    # env_file:
    #   - ./nodejs/.env
    environment:
      - PORT=3001
      - TELEMETRY_ENABLED=true
      - OTEL_SERVICE_NAME=my-site
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel-collector:4318/v1/traces
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://otel-collector:4318/v1/metrics
    # volumes:
    #   - ./nodejs/data:/app/data
    networks:
      - web
    depends_on:
      - otel-collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./otel/otelcol-config.yaml:/etc/otelcol/config.yaml:ro
    networks: [web]
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"   # Jaeger UI
      - "4317:4317"     # OTLP gRPC ingest
      - "4318:4318"     # OTLP HTTP ingest
    networks: [web]
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./grafana/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks: [web]
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    networks: [web]
    ports:
      - "3002:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks: [web]

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./grafana/promtail.yaml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml
    networks: [web]
    depends_on:
      - loki

networks:
  web:
    driver: bridge

volumes:
  grafana-data: